// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: constants.proto

package espidf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Allowed values for the status
// of a protocomm instance
type Status int32

const (
	Status_Success          Status = 0
	Status_InvalidSecScheme Status = 1
	Status_InvalidProto     Status = 2
	Status_TooManySessions  Status = 3
	Status_InvalidArgument  Status = 4
	Status_InternalError    Status = 5
	Status_CryptoError      Status = 6
	Status_InvalidSession   Status = 7
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Success",
		1: "InvalidSecScheme",
		2: "InvalidProto",
		3: "TooManySessions",
		4: "InvalidArgument",
		5: "InternalError",
		6: "CryptoError",
		7: "InvalidSession",
	}
	Status_value = map[string]int32{
		"Success":          0,
		"InvalidSecScheme": 1,
		"InvalidProto":     2,
		"TooManySessions":  3,
		"InvalidArgument":  4,
		"InternalError":    5,
		"CryptoError":      6,
		"InvalidSession":   7,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_constants_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_constants_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_constants_proto_rawDescGZIP(), []int{0}
}

var File_constants_proto protoreflect.FileDescriptor

const file_constants_proto_rawDesc = "" +
	"\n" +
	"\x0fconstants.proto*\x9f\x01\n" +
	"\x06Status\x12\v\n" +
	"\aSuccess\x10\x00\x12\x14\n" +
	"\x10InvalidSecScheme\x10\x01\x12\x10\n" +
	"\fInvalidProto\x10\x02\x12\x13\n" +
	"\x0fTooManySessions\x10\x03\x12\x13\n" +
	"\x0fInvalidArgument\x10\x04\x12\x11\n" +
	"\rInternalError\x10\x05\x12\x0f\n" +
	"\vCryptoError\x10\x06\x12\x12\n" +
	"\x0eInvalidSession\x10\aBSZQgithub.com/go-go-golems/almanach/internal/provisioning/native/proto/espidf;espidfb\x06proto3"

var (
	file_constants_proto_rawDescOnce sync.Once
	file_constants_proto_rawDescData []byte
)

func file_constants_proto_rawDescGZIP() []byte {
	file_constants_proto_rawDescOnce.Do(func() {
		file_constants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_constants_proto_rawDesc), len(file_constants_proto_rawDesc)))
	})
	return file_constants_proto_rawDescData
}

var file_constants_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constants_proto_goTypes = []any{
	(Status)(0), // 0: Status
}
var file_constants_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constants_proto_init() }
func file_constants_proto_init() {
	if File_constants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_constants_proto_rawDesc), len(file_constants_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constants_proto_goTypes,
		DependencyIndexes: file_constants_proto_depIdxs,
		EnumInfos:         file_constants_proto_enumTypes,
	}.Build()
	File_constants_proto = out.File
	file_constants_proto_goTypes = nil
	file_constants_proto_depIdxs = nil
}
