// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sec0.proto

package espidf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A message must be of type Cmd or Resp
type Sec0MsgType int32

const (
	Sec0MsgType_S0_Session_Command  Sec0MsgType = 0
	Sec0MsgType_S0_Session_Response Sec0MsgType = 1
)

// Enum value maps for Sec0MsgType.
var (
	Sec0MsgType_name = map[int32]string{
		0: "S0_Session_Command",
		1: "S0_Session_Response",
	}
	Sec0MsgType_value = map[string]int32{
		"S0_Session_Command":  0,
		"S0_Session_Response": 1,
	}
)

func (x Sec0MsgType) Enum() *Sec0MsgType {
	p := new(Sec0MsgType)
	*p = x
	return p
}

func (x Sec0MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sec0MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_sec0_proto_enumTypes[0].Descriptor()
}

func (Sec0MsgType) Type() protoreflect.EnumType {
	return &file_sec0_proto_enumTypes[0]
}

func (x Sec0MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sec0MsgType.Descriptor instead.
func (Sec0MsgType) EnumDescriptor() ([]byte, []int) {
	return file_sec0_proto_rawDescGZIP(), []int{0}
}

// Data structure of Session command/request packet
type S0SessionCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S0SessionCmd) Reset() {
	*x = S0SessionCmd{}
	mi := &file_sec0_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S0SessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S0SessionCmd) ProtoMessage() {}

func (x *S0SessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_sec0_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S0SessionCmd.ProtoReflect.Descriptor instead.
func (*S0SessionCmd) Descriptor() ([]byte, []int) {
	return file_sec0_proto_rawDescGZIP(), []int{0}
}

// Data structure of Session response packet
type S0SessionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S0SessionResp) Reset() {
	*x = S0SessionResp{}
	mi := &file_sec0_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S0SessionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S0SessionResp) ProtoMessage() {}

func (x *S0SessionResp) ProtoReflect() protoreflect.Message {
	mi := &file_sec0_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S0SessionResp.ProtoReflect.Descriptor instead.
func (*S0SessionResp) Descriptor() ([]byte, []int) {
	return file_sec0_proto_rawDescGZIP(), []int{1}
}

func (x *S0SessionResp) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

// Payload structure of session data
type Sec0Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Msg   Sec0MsgType            `protobuf:"varint,1,opt,name=msg,proto3,enum=Sec0MsgType" json:"msg,omitempty"` //!< Type of message
	// Types that are valid to be assigned to Payload:
	//
	//	*Sec0Payload_Sc
	//	*Sec0Payload_Sr
	Payload       isSec0Payload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sec0Payload) Reset() {
	*x = Sec0Payload{}
	mi := &file_sec0_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sec0Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sec0Payload) ProtoMessage() {}

func (x *Sec0Payload) ProtoReflect() protoreflect.Message {
	mi := &file_sec0_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sec0Payload.ProtoReflect.Descriptor instead.
func (*Sec0Payload) Descriptor() ([]byte, []int) {
	return file_sec0_proto_rawDescGZIP(), []int{2}
}

func (x *Sec0Payload) GetMsg() Sec0MsgType {
	if x != nil {
		return x.Msg
	}
	return Sec0MsgType_S0_Session_Command
}

func (x *Sec0Payload) GetPayload() isSec0Payload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Sec0Payload) GetSc() *S0SessionCmd {
	if x != nil {
		if x, ok := x.Payload.(*Sec0Payload_Sc); ok {
			return x.Sc
		}
	}
	return nil
}

func (x *Sec0Payload) GetSr() *S0SessionResp {
	if x != nil {
		if x, ok := x.Payload.(*Sec0Payload_Sr); ok {
			return x.Sr
		}
	}
	return nil
}

type isSec0Payload_Payload interface {
	isSec0Payload_Payload()
}

type Sec0Payload_Sc struct {
	Sc *S0SessionCmd `protobuf:"bytes,20,opt,name=sc,proto3,oneof"` //!< Payload data interpreted as Cmd
}

type Sec0Payload_Sr struct {
	Sr *S0SessionResp `protobuf:"bytes,21,opt,name=sr,proto3,oneof"` //!< Payload data interpreted as Resp
}

func (*Sec0Payload_Sc) isSec0Payload_Payload() {}

func (*Sec0Payload_Sr) isSec0Payload_Payload() {}

var File_sec0_proto protoreflect.FileDescriptor

const file_sec0_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sec0.proto\x1a\x0fconstants.proto\"\x0e\n" +
	"\fS0SessionCmd\"0\n" +
	"\rS0SessionResp\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\x0e2\a.StatusR\x06status\"{\n" +
	"\vSec0Payload\x12\x1e\n" +
	"\x03msg\x18\x01 \x01(\x0e2\f.Sec0MsgTypeR\x03msg\x12\x1f\n" +
	"\x02sc\x18\x14 \x01(\v2\r.S0SessionCmdH\x00R\x02sc\x12 \n" +
	"\x02sr\x18\x15 \x01(\v2\x0e.S0SessionRespH\x00R\x02srB\t\n" +
	"\apayload*>\n" +
	"\vSec0MsgType\x12\x16\n" +
	"\x12S0_Session_Command\x10\x00\x12\x17\n" +
	"\x13S0_Session_Response\x10\x01BSZQgithub.com/go-go-golems/almanach/internal/provisioning/native/proto/espidf;espidfb\x06proto3"

var (
	file_sec0_proto_rawDescOnce sync.Once
	file_sec0_proto_rawDescData []byte
)

func file_sec0_proto_rawDescGZIP() []byte {
	file_sec0_proto_rawDescOnce.Do(func() {
		file_sec0_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sec0_proto_rawDesc), len(file_sec0_proto_rawDesc)))
	})
	return file_sec0_proto_rawDescData
}

var file_sec0_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sec0_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sec0_proto_goTypes = []any{
	(Sec0MsgType)(0),      // 0: Sec0MsgType
	(*S0SessionCmd)(nil),  // 1: S0SessionCmd
	(*S0SessionResp)(nil), // 2: S0SessionResp
	(*Sec0Payload)(nil),   // 3: Sec0Payload
	(Status)(0),           // 4: Status
}
var file_sec0_proto_depIdxs = []int32{
	4, // 0: S0SessionResp.status:type_name -> Status
	0, // 1: Sec0Payload.msg:type_name -> Sec0MsgType
	1, // 2: Sec0Payload.sc:type_name -> S0SessionCmd
	2, // 3: Sec0Payload.sr:type_name -> S0SessionResp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sec0_proto_init() }
func file_sec0_proto_init() {
	if File_sec0_proto != nil {
		return
	}
	file_constants_proto_init()
	file_sec0_proto_msgTypes[2].OneofWrappers = []any{
		(*Sec0Payload_Sc)(nil),
		(*Sec0Payload_Sr)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sec0_proto_rawDesc), len(file_sec0_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sec0_proto_goTypes,
		DependencyIndexes: file_sec0_proto_depIdxs,
		EnumInfos:         file_sec0_proto_enumTypes,
		MessageInfos:      file_sec0_proto_msgTypes,
	}.Build()
	File_sec0_proto = out.File
	file_sec0_proto_goTypes = nil
	file_sec0_proto_depIdxs = nil
}
