// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sec1.proto

package espidf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A message must be of type Cmd0 / Cmd1 / Resp0 / Resp1
type Sec1MsgType int32

const (
	Sec1MsgType_Session_Command0  Sec1MsgType = 0
	Sec1MsgType_Session_Response0 Sec1MsgType = 1
	Sec1MsgType_Session_Command1  Sec1MsgType = 2
	Sec1MsgType_Session_Response1 Sec1MsgType = 3
)

// Enum value maps for Sec1MsgType.
var (
	Sec1MsgType_name = map[int32]string{
		0: "Session_Command0",
		1: "Session_Response0",
		2: "Session_Command1",
		3: "Session_Response1",
	}
	Sec1MsgType_value = map[string]int32{
		"Session_Command0":  0,
		"Session_Response0": 1,
		"Session_Command1":  2,
		"Session_Response1": 3,
	}
)

func (x Sec1MsgType) Enum() *Sec1MsgType {
	p := new(Sec1MsgType)
	*p = x
	return p
}

func (x Sec1MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sec1MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_sec1_proto_enumTypes[0].Descriptor()
}

func (Sec1MsgType) Type() protoreflect.EnumType {
	return &file_sec1_proto_enumTypes[0]
}

func (x Sec1MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sec1MsgType.Descriptor instead.
func (Sec1MsgType) EnumDescriptor() ([]byte, []int) {
	return file_sec1_proto_rawDescGZIP(), []int{0}
}

// Data structure of Session command1 packet
type SessionCmd1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientVerifyData []byte                 `protobuf:"bytes,2,opt,name=client_verify_data,json=clientVerifyData,proto3" json:"client_verify_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionCmd1) Reset() {
	*x = SessionCmd1{}
	mi := &file_sec1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCmd1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCmd1) ProtoMessage() {}

func (x *SessionCmd1) ProtoReflect() protoreflect.Message {
	mi := &file_sec1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCmd1.ProtoReflect.Descriptor instead.
func (*SessionCmd1) Descriptor() ([]byte, []int) {
	return file_sec1_proto_rawDescGZIP(), []int{0}
}

func (x *SessionCmd1) GetClientVerifyData() []byte {
	if x != nil {
		return x.ClientVerifyData
	}
	return nil
}

// Data structure of Session response1 packet
type SessionResp1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	DeviceVerifyData []byte                 `protobuf:"bytes,3,opt,name=device_verify_data,json=deviceVerifyData,proto3" json:"device_verify_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionResp1) Reset() {
	*x = SessionResp1{}
	mi := &file_sec1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResp1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResp1) ProtoMessage() {}

func (x *SessionResp1) ProtoReflect() protoreflect.Message {
	mi := &file_sec1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResp1.ProtoReflect.Descriptor instead.
func (*SessionResp1) Descriptor() ([]byte, []int) {
	return file_sec1_proto_rawDescGZIP(), []int{1}
}

func (x *SessionResp1) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

func (x *SessionResp1) GetDeviceVerifyData() []byte {
	if x != nil {
		return x.DeviceVerifyData
	}
	return nil
}

// Data structure of Session command0 packet
type SessionCmd0 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientPubkey  []byte                 `protobuf:"bytes,1,opt,name=client_pubkey,json=clientPubkey,proto3" json:"client_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCmd0) Reset() {
	*x = SessionCmd0{}
	mi := &file_sec1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCmd0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCmd0) ProtoMessage() {}

func (x *SessionCmd0) ProtoReflect() protoreflect.Message {
	mi := &file_sec1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCmd0.ProtoReflect.Descriptor instead.
func (*SessionCmd0) Descriptor() ([]byte, []int) {
	return file_sec1_proto_rawDescGZIP(), []int{2}
}

func (x *SessionCmd0) GetClientPubkey() []byte {
	if x != nil {
		return x.ClientPubkey
	}
	return nil
}

// Data structure of Session response0 packet
type SessionResp0 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	DevicePubkey  []byte                 `protobuf:"bytes,2,opt,name=device_pubkey,json=devicePubkey,proto3" json:"device_pubkey,omitempty"`
	DeviceRandom  []byte                 `protobuf:"bytes,3,opt,name=device_random,json=deviceRandom,proto3" json:"device_random,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResp0) Reset() {
	*x = SessionResp0{}
	mi := &file_sec1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResp0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResp0) ProtoMessage() {}

func (x *SessionResp0) ProtoReflect() protoreflect.Message {
	mi := &file_sec1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResp0.ProtoReflect.Descriptor instead.
func (*SessionResp0) Descriptor() ([]byte, []int) {
	return file_sec1_proto_rawDescGZIP(), []int{3}
}

func (x *SessionResp0) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

func (x *SessionResp0) GetDevicePubkey() []byte {
	if x != nil {
		return x.DevicePubkey
	}
	return nil
}

func (x *SessionResp0) GetDeviceRandom() []byte {
	if x != nil {
		return x.DeviceRandom
	}
	return nil
}

// Payload structure of session data
type Sec1Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Msg   Sec1MsgType            `protobuf:"varint,1,opt,name=msg,proto3,enum=Sec1MsgType" json:"msg,omitempty"` //!< Type of message
	// Types that are valid to be assigned to Payload:
	//
	//	*Sec1Payload_Sc0
	//	*Sec1Payload_Sr0
	//	*Sec1Payload_Sc1
	//	*Sec1Payload_Sr1
	Payload       isSec1Payload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sec1Payload) Reset() {
	*x = Sec1Payload{}
	mi := &file_sec1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sec1Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sec1Payload) ProtoMessage() {}

func (x *Sec1Payload) ProtoReflect() protoreflect.Message {
	mi := &file_sec1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sec1Payload.ProtoReflect.Descriptor instead.
func (*Sec1Payload) Descriptor() ([]byte, []int) {
	return file_sec1_proto_rawDescGZIP(), []int{4}
}

func (x *Sec1Payload) GetMsg() Sec1MsgType {
	if x != nil {
		return x.Msg
	}
	return Sec1MsgType_Session_Command0
}

func (x *Sec1Payload) GetPayload() isSec1Payload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Sec1Payload) GetSc0() *SessionCmd0 {
	if x != nil {
		if x, ok := x.Payload.(*Sec1Payload_Sc0); ok {
			return x.Sc0
		}
	}
	return nil
}

func (x *Sec1Payload) GetSr0() *SessionResp0 {
	if x != nil {
		if x, ok := x.Payload.(*Sec1Payload_Sr0); ok {
			return x.Sr0
		}
	}
	return nil
}

func (x *Sec1Payload) GetSc1() *SessionCmd1 {
	if x != nil {
		if x, ok := x.Payload.(*Sec1Payload_Sc1); ok {
			return x.Sc1
		}
	}
	return nil
}

func (x *Sec1Payload) GetSr1() *SessionResp1 {
	if x != nil {
		if x, ok := x.Payload.(*Sec1Payload_Sr1); ok {
			return x.Sr1
		}
	}
	return nil
}

type isSec1Payload_Payload interface {
	isSec1Payload_Payload()
}

type Sec1Payload_Sc0 struct {
	Sc0 *SessionCmd0 `protobuf:"bytes,20,opt,name=sc0,proto3,oneof"` //!< Payload data interpreted as Cmd0
}

type Sec1Payload_Sr0 struct {
	Sr0 *SessionResp0 `protobuf:"bytes,21,opt,name=sr0,proto3,oneof"` //!< Payload data interpreted as Resp0
}

type Sec1Payload_Sc1 struct {
	Sc1 *SessionCmd1 `protobuf:"bytes,22,opt,name=sc1,proto3,oneof"` //!< Payload data interpreted as Cmd1
}

type Sec1Payload_Sr1 struct {
	Sr1 *SessionResp1 `protobuf:"bytes,23,opt,name=sr1,proto3,oneof"` //!< Payload data interpreted as Resp1
}

func (*Sec1Payload_Sc0) isSec1Payload_Payload() {}

func (*Sec1Payload_Sr0) isSec1Payload_Payload() {}

func (*Sec1Payload_Sc1) isSec1Payload_Payload() {}

func (*Sec1Payload_Sr1) isSec1Payload_Payload() {}

var File_sec1_proto protoreflect.FileDescriptor

const file_sec1_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sec1.proto\x1a\x0fconstants.proto\";\n" +
	"\vSessionCmd1\x12,\n" +
	"\x12client_verify_data\x18\x02 \x01(\fR\x10clientVerifyData\"]\n" +
	"\fSessionResp1\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\x0e2\a.StatusR\x06status\x12,\n" +
	"\x12device_verify_data\x18\x03 \x01(\fR\x10deviceVerifyData\"2\n" +
	"\vSessionCmd0\x12#\n" +
	"\rclient_pubkey\x18\x01 \x01(\fR\fclientPubkey\"y\n" +
	"\fSessionResp0\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\x0e2\a.StatusR\x06status\x12#\n" +
	"\rdevice_pubkey\x18\x02 \x01(\fR\fdevicePubkey\x12#\n" +
	"\rdevice_random\x18\x03 \x01(\fR\fdeviceRandom\"\xc2\x01\n" +
	"\vSec1Payload\x12\x1e\n" +
	"\x03msg\x18\x01 \x01(\x0e2\f.Sec1MsgTypeR\x03msg\x12 \n" +
	"\x03sc0\x18\x14 \x01(\v2\f.SessionCmd0H\x00R\x03sc0\x12!\n" +
	"\x03sr0\x18\x15 \x01(\v2\r.SessionResp0H\x00R\x03sr0\x12 \n" +
	"\x03sc1\x18\x16 \x01(\v2\f.SessionCmd1H\x00R\x03sc1\x12!\n" +
	"\x03sr1\x18\x17 \x01(\v2\r.SessionResp1H\x00R\x03sr1B\t\n" +
	"\apayload*g\n" +
	"\vSec1MsgType\x12\x14\n" +
	"\x10Session_Command0\x10\x00\x12\x15\n" +
	"\x11Session_Response0\x10\x01\x12\x14\n" +
	"\x10Session_Command1\x10\x02\x12\x15\n" +
	"\x11Session_Response1\x10\x03BSZQgithub.com/go-go-golems/almanach/internal/provisioning/native/proto/espidf;espidfb\x06proto3"

var (
	file_sec1_proto_rawDescOnce sync.Once
	file_sec1_proto_rawDescData []byte
)

func file_sec1_proto_rawDescGZIP() []byte {
	file_sec1_proto_rawDescOnce.Do(func() {
		file_sec1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sec1_proto_rawDesc), len(file_sec1_proto_rawDesc)))
	})
	return file_sec1_proto_rawDescData
}

var file_sec1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sec1_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sec1_proto_goTypes = []any{
	(Sec1MsgType)(0),     // 0: Sec1MsgType
	(*SessionCmd1)(nil),  // 1: SessionCmd1
	(*SessionResp1)(nil), // 2: SessionResp1
	(*SessionCmd0)(nil),  // 3: SessionCmd0
	(*SessionResp0)(nil), // 4: SessionResp0
	(*Sec1Payload)(nil),  // 5: Sec1Payload
	(Status)(0),          // 6: Status
}
var file_sec1_proto_depIdxs = []int32{
	6, // 0: SessionResp1.status:type_name -> Status
	6, // 1: SessionResp0.status:type_name -> Status
	0, // 2: Sec1Payload.msg:type_name -> Sec1MsgType
	3, // 3: Sec1Payload.sc0:type_name -> SessionCmd0
	4, // 4: Sec1Payload.sr0:type_name -> SessionResp0
	1, // 5: Sec1Payload.sc1:type_name -> SessionCmd1
	2, // 6: Sec1Payload.sr1:type_name -> SessionResp1
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sec1_proto_init() }
func file_sec1_proto_init() {
	if File_sec1_proto != nil {
		return
	}
	file_constants_proto_init()
	file_sec1_proto_msgTypes[4].OneofWrappers = []any{
		(*Sec1Payload_Sc0)(nil),
		(*Sec1Payload_Sr0)(nil),
		(*Sec1Payload_Sc1)(nil),
		(*Sec1Payload_Sr1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sec1_proto_rawDesc), len(file_sec1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sec1_proto_goTypes,
		DependencyIndexes: file_sec1_proto_depIdxs,
		EnumInfos:         file_sec1_proto_enumTypes,
		MessageInfos:      file_sec1_proto_msgTypes,
	}.Build()
	File_sec1_proto = out.File
	file_sec1_proto_goTypes = nil
	file_sec1_proto_depIdxs = nil
}
