// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sec2.proto

package espidf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A message must be of type Cmd0 / Cmd1 / Resp0 / Resp1
type Sec2MsgType int32

const (
	Sec2MsgType_S2Session_Command0  Sec2MsgType = 0
	Sec2MsgType_S2Session_Response0 Sec2MsgType = 1
	Sec2MsgType_S2Session_Command1  Sec2MsgType = 2
	Sec2MsgType_S2Session_Response1 Sec2MsgType = 3
)

// Enum value maps for Sec2MsgType.
var (
	Sec2MsgType_name = map[int32]string{
		0: "S2Session_Command0",
		1: "S2Session_Response0",
		2: "S2Session_Command1",
		3: "S2Session_Response1",
	}
	Sec2MsgType_value = map[string]int32{
		"S2Session_Command0":  0,
		"S2Session_Response0": 1,
		"S2Session_Command1":  2,
		"S2Session_Response1": 3,
	}
)

func (x Sec2MsgType) Enum() *Sec2MsgType {
	p := new(Sec2MsgType)
	*p = x
	return p
}

func (x Sec2MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sec2MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_sec2_proto_enumTypes[0].Descriptor()
}

func (Sec2MsgType) Type() protoreflect.EnumType {
	return &file_sec2_proto_enumTypes[0]
}

func (x Sec2MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sec2MsgType.Descriptor instead.
func (Sec2MsgType) EnumDescriptor() ([]byte, []int) {
	return file_sec2_proto_rawDescGZIP(), []int{0}
}

// Data structure of Session command0 packet
type S2SessionCmd0 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientUsername []byte                 `protobuf:"bytes,1,opt,name=client_username,json=clientUsername,proto3" json:"client_username,omitempty"`
	ClientPubkey   []byte                 `protobuf:"bytes,2,opt,name=client_pubkey,json=clientPubkey,proto3" json:"client_pubkey,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *S2SessionCmd0) Reset() {
	*x = S2SessionCmd0{}
	mi := &file_sec2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SessionCmd0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SessionCmd0) ProtoMessage() {}

func (x *S2SessionCmd0) ProtoReflect() protoreflect.Message {
	mi := &file_sec2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SessionCmd0.ProtoReflect.Descriptor instead.
func (*S2SessionCmd0) Descriptor() ([]byte, []int) {
	return file_sec2_proto_rawDescGZIP(), []int{0}
}

func (x *S2SessionCmd0) GetClientUsername() []byte {
	if x != nil {
		return x.ClientUsername
	}
	return nil
}

func (x *S2SessionCmd0) GetClientPubkey() []byte {
	if x != nil {
		return x.ClientPubkey
	}
	return nil
}

// Data structure of Session response0 packet
type S2SessionResp0 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	DevicePubkey  []byte                 `protobuf:"bytes,2,opt,name=device_pubkey,json=devicePubkey,proto3" json:"device_pubkey,omitempty"`
	DeviceSalt    []byte                 `protobuf:"bytes,3,opt,name=device_salt,json=deviceSalt,proto3" json:"device_salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2SessionResp0) Reset() {
	*x = S2SessionResp0{}
	mi := &file_sec2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SessionResp0) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SessionResp0) ProtoMessage() {}

func (x *S2SessionResp0) ProtoReflect() protoreflect.Message {
	mi := &file_sec2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SessionResp0.ProtoReflect.Descriptor instead.
func (*S2SessionResp0) Descriptor() ([]byte, []int) {
	return file_sec2_proto_rawDescGZIP(), []int{1}
}

func (x *S2SessionResp0) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

func (x *S2SessionResp0) GetDevicePubkey() []byte {
	if x != nil {
		return x.DevicePubkey
	}
	return nil
}

func (x *S2SessionResp0) GetDeviceSalt() []byte {
	if x != nil {
		return x.DeviceSalt
	}
	return nil
}

// Data structure of Session command1 packet
type S2SessionCmd1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientProof   []byte                 `protobuf:"bytes,1,opt,name=client_proof,json=clientProof,proto3" json:"client_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2SessionCmd1) Reset() {
	*x = S2SessionCmd1{}
	mi := &file_sec2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SessionCmd1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SessionCmd1) ProtoMessage() {}

func (x *S2SessionCmd1) ProtoReflect() protoreflect.Message {
	mi := &file_sec2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SessionCmd1.ProtoReflect.Descriptor instead.
func (*S2SessionCmd1) Descriptor() ([]byte, []int) {
	return file_sec2_proto_rawDescGZIP(), []int{2}
}

func (x *S2SessionCmd1) GetClientProof() []byte {
	if x != nil {
		return x.ClientProof
	}
	return nil
}

// Data structure of Session response1 packet
type S2SessionResp1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	DeviceProof   []byte                 `protobuf:"bytes,2,opt,name=device_proof,json=deviceProof,proto3" json:"device_proof,omitempty"`
	DeviceNonce   []byte                 `protobuf:"bytes,3,opt,name=device_nonce,json=deviceNonce,proto3" json:"device_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2SessionResp1) Reset() {
	*x = S2SessionResp1{}
	mi := &file_sec2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2SessionResp1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2SessionResp1) ProtoMessage() {}

func (x *S2SessionResp1) ProtoReflect() protoreflect.Message {
	mi := &file_sec2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2SessionResp1.ProtoReflect.Descriptor instead.
func (*S2SessionResp1) Descriptor() ([]byte, []int) {
	return file_sec2_proto_rawDescGZIP(), []int{3}
}

func (x *S2SessionResp1) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

func (x *S2SessionResp1) GetDeviceProof() []byte {
	if x != nil {
		return x.DeviceProof
	}
	return nil
}

func (x *S2SessionResp1) GetDeviceNonce() []byte {
	if x != nil {
		return x.DeviceNonce
	}
	return nil
}

// Payload structure of session data
type Sec2Payload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Msg   Sec2MsgType            `protobuf:"varint,1,opt,name=msg,proto3,enum=Sec2MsgType" json:"msg,omitempty"` //!< Type of message
	// Types that are valid to be assigned to Payload:
	//
	//	*Sec2Payload_Sc0
	//	*Sec2Payload_Sr0
	//	*Sec2Payload_Sc1
	//	*Sec2Payload_Sr1
	Payload       isSec2Payload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sec2Payload) Reset() {
	*x = Sec2Payload{}
	mi := &file_sec2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sec2Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sec2Payload) ProtoMessage() {}

func (x *Sec2Payload) ProtoReflect() protoreflect.Message {
	mi := &file_sec2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sec2Payload.ProtoReflect.Descriptor instead.
func (*Sec2Payload) Descriptor() ([]byte, []int) {
	return file_sec2_proto_rawDescGZIP(), []int{4}
}

func (x *Sec2Payload) GetMsg() Sec2MsgType {
	if x != nil {
		return x.Msg
	}
	return Sec2MsgType_S2Session_Command0
}

func (x *Sec2Payload) GetPayload() isSec2Payload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Sec2Payload) GetSc0() *S2SessionCmd0 {
	if x != nil {
		if x, ok := x.Payload.(*Sec2Payload_Sc0); ok {
			return x.Sc0
		}
	}
	return nil
}

func (x *Sec2Payload) GetSr0() *S2SessionResp0 {
	if x != nil {
		if x, ok := x.Payload.(*Sec2Payload_Sr0); ok {
			return x.Sr0
		}
	}
	return nil
}

func (x *Sec2Payload) GetSc1() *S2SessionCmd1 {
	if x != nil {
		if x, ok := x.Payload.(*Sec2Payload_Sc1); ok {
			return x.Sc1
		}
	}
	return nil
}

func (x *Sec2Payload) GetSr1() *S2SessionResp1 {
	if x != nil {
		if x, ok := x.Payload.(*Sec2Payload_Sr1); ok {
			return x.Sr1
		}
	}
	return nil
}

type isSec2Payload_Payload interface {
	isSec2Payload_Payload()
}

type Sec2Payload_Sc0 struct {
	Sc0 *S2SessionCmd0 `protobuf:"bytes,20,opt,name=sc0,proto3,oneof"` //!< Payload data interpreted as Cmd0
}

type Sec2Payload_Sr0 struct {
	Sr0 *S2SessionResp0 `protobuf:"bytes,21,opt,name=sr0,proto3,oneof"` //!< Payload data interpreted as Resp0
}

type Sec2Payload_Sc1 struct {
	Sc1 *S2SessionCmd1 `protobuf:"bytes,22,opt,name=sc1,proto3,oneof"` //!< Payload data interpreted as Cmd1
}

type Sec2Payload_Sr1 struct {
	Sr1 *S2SessionResp1 `protobuf:"bytes,23,opt,name=sr1,proto3,oneof"` //!< Payload data interpreted as Resp1
}

func (*Sec2Payload_Sc0) isSec2Payload_Payload() {}

func (*Sec2Payload_Sr0) isSec2Payload_Payload() {}

func (*Sec2Payload_Sc1) isSec2Payload_Payload() {}

func (*Sec2Payload_Sr1) isSec2Payload_Payload() {}

var File_sec2_proto protoreflect.FileDescriptor

const file_sec2_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"sec2.proto\x1a\x0fconstants.proto\"]\n" +
	"\rS2SessionCmd0\x12'\n" +
	"\x0fclient_username\x18\x01 \x01(\fR\x0eclientUsername\x12#\n" +
	"\rclient_pubkey\x18\x02 \x01(\fR\fclientPubkey\"w\n" +
	"\x0eS2SessionResp0\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\x0e2\a.StatusR\x06status\x12#\n" +
	"\rdevice_pubkey\x18\x02 \x01(\fR\fdevicePubkey\x12\x1f\n" +
	"\vdevice_salt\x18\x03 \x01(\fR\n" +
	"deviceSalt\"2\n" +
	"\rS2SessionCmd1\x12!\n" +
	"\fclient_proof\x18\x01 \x01(\fR\vclientProof\"w\n" +
	"\x0eS2SessionResp1\x12\x1f\n" +
	"\x06status\x18\x01 \x01(\x0e2\a.StatusR\x06status\x12!\n" +
	"\fdevice_proof\x18\x02 \x01(\fR\vdeviceProof\x12!\n" +
	"\fdevice_nonce\x18\x03 \x01(\fR\vdeviceNonce\"\xca\x01\n" +
	"\vSec2Payload\x12\x1e\n" +
	"\x03msg\x18\x01 \x01(\x0e2\f.Sec2MsgTypeR\x03msg\x12\"\n" +
	"\x03sc0\x18\x14 \x01(\v2\x0e.S2SessionCmd0H\x00R\x03sc0\x12#\n" +
	"\x03sr0\x18\x15 \x01(\v2\x0f.S2SessionResp0H\x00R\x03sr0\x12\"\n" +
	"\x03sc1\x18\x16 \x01(\v2\x0e.S2SessionCmd1H\x00R\x03sc1\x12#\n" +
	"\x03sr1\x18\x17 \x01(\v2\x0f.S2SessionResp1H\x00R\x03sr1B\t\n" +
	"\apayload*o\n" +
	"\vSec2MsgType\x12\x16\n" +
	"\x12S2Session_Command0\x10\x00\x12\x17\n" +
	"\x13S2Session_Response0\x10\x01\x12\x16\n" +
	"\x12S2Session_Command1\x10\x02\x12\x17\n" +
	"\x13S2Session_Response1\x10\x03BSZQgithub.com/go-go-golems/almanach/internal/provisioning/native/proto/espidf;espidfb\x06proto3"

var (
	file_sec2_proto_rawDescOnce sync.Once
	file_sec2_proto_rawDescData []byte
)

func file_sec2_proto_rawDescGZIP() []byte {
	file_sec2_proto_rawDescOnce.Do(func() {
		file_sec2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sec2_proto_rawDesc), len(file_sec2_proto_rawDesc)))
	})
	return file_sec2_proto_rawDescData
}

var file_sec2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sec2_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sec2_proto_goTypes = []any{
	(Sec2MsgType)(0),       // 0: Sec2MsgType
	(*S2SessionCmd0)(nil),  // 1: S2SessionCmd0
	(*S2SessionResp0)(nil), // 2: S2SessionResp0
	(*S2SessionCmd1)(nil),  // 3: S2SessionCmd1
	(*S2SessionResp1)(nil), // 4: S2SessionResp1
	(*Sec2Payload)(nil),    // 5: Sec2Payload
	(Status)(0),            // 6: Status
}
var file_sec2_proto_depIdxs = []int32{
	6, // 0: S2SessionResp0.status:type_name -> Status
	6, // 1: S2SessionResp1.status:type_name -> Status
	0, // 2: Sec2Payload.msg:type_name -> Sec2MsgType
	1, // 3: Sec2Payload.sc0:type_name -> S2SessionCmd0
	2, // 4: Sec2Payload.sr0:type_name -> S2SessionResp0
	3, // 5: Sec2Payload.sc1:type_name -> S2SessionCmd1
	4, // 6: Sec2Payload.sr1:type_name -> S2SessionResp1
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_sec2_proto_init() }
func file_sec2_proto_init() {
	if File_sec2_proto != nil {
		return
	}
	file_constants_proto_init()
	file_sec2_proto_msgTypes[4].OneofWrappers = []any{
		(*Sec2Payload_Sc0)(nil),
		(*Sec2Payload_Sr0)(nil),
		(*Sec2Payload_Sc1)(nil),
		(*Sec2Payload_Sr1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sec2_proto_rawDesc), len(file_sec2_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sec2_proto_goTypes,
		DependencyIndexes: file_sec2_proto_depIdxs,
		EnumInfos:         file_sec2_proto_enumTypes,
		MessageInfos:      file_sec2_proto_msgTypes,
	}.Build()
	File_sec2_proto = out.File
	file_sec2_proto_goTypes = nil
	file_sec2_proto_depIdxs = nil
}
