// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi_ctrl.proto

package espidf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WiFiCtrlMsgType int32

const (
	WiFiCtrlMsgType_TypeCtrlReserved   WiFiCtrlMsgType = 0
	WiFiCtrlMsgType_TypeCmdCtrlReset   WiFiCtrlMsgType = 1
	WiFiCtrlMsgType_TypeRespCtrlReset  WiFiCtrlMsgType = 2
	WiFiCtrlMsgType_TypeCmdCtrlReprov  WiFiCtrlMsgType = 3
	WiFiCtrlMsgType_TypeRespCtrlReprov WiFiCtrlMsgType = 4
)

// Enum value maps for WiFiCtrlMsgType.
var (
	WiFiCtrlMsgType_name = map[int32]string{
		0: "TypeCtrlReserved",
		1: "TypeCmdCtrlReset",
		2: "TypeRespCtrlReset",
		3: "TypeCmdCtrlReprov",
		4: "TypeRespCtrlReprov",
	}
	WiFiCtrlMsgType_value = map[string]int32{
		"TypeCtrlReserved":   0,
		"TypeCmdCtrlReset":   1,
		"TypeRespCtrlReset":  2,
		"TypeCmdCtrlReprov":  3,
		"TypeRespCtrlReprov": 4,
	}
)

func (x WiFiCtrlMsgType) Enum() *WiFiCtrlMsgType {
	p := new(WiFiCtrlMsgType)
	*p = x
	return p
}

func (x WiFiCtrlMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WiFiCtrlMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_ctrl_proto_enumTypes[0].Descriptor()
}

func (WiFiCtrlMsgType) Type() protoreflect.EnumType {
	return &file_wifi_ctrl_proto_enumTypes[0]
}

func (x WiFiCtrlMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WiFiCtrlMsgType.Descriptor instead.
func (WiFiCtrlMsgType) EnumDescriptor() ([]byte, []int) {
	return file_wifi_ctrl_proto_rawDescGZIP(), []int{0}
}

type CmdCtrlReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdCtrlReset) Reset() {
	*x = CmdCtrlReset{}
	mi := &file_wifi_ctrl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdCtrlReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdCtrlReset) ProtoMessage() {}

func (x *CmdCtrlReset) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_ctrl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdCtrlReset.ProtoReflect.Descriptor instead.
func (*CmdCtrlReset) Descriptor() ([]byte, []int) {
	return file_wifi_ctrl_proto_rawDescGZIP(), []int{0}
}

type RespCtrlReset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespCtrlReset) Reset() {
	*x = RespCtrlReset{}
	mi := &file_wifi_ctrl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespCtrlReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespCtrlReset) ProtoMessage() {}

func (x *RespCtrlReset) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_ctrl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespCtrlReset.ProtoReflect.Descriptor instead.
func (*RespCtrlReset) Descriptor() ([]byte, []int) {
	return file_wifi_ctrl_proto_rawDescGZIP(), []int{1}
}

type CmdCtrlReprov struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdCtrlReprov) Reset() {
	*x = CmdCtrlReprov{}
	mi := &file_wifi_ctrl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdCtrlReprov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdCtrlReprov) ProtoMessage() {}

func (x *CmdCtrlReprov) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_ctrl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdCtrlReprov.ProtoReflect.Descriptor instead.
func (*CmdCtrlReprov) Descriptor() ([]byte, []int) {
	return file_wifi_ctrl_proto_rawDescGZIP(), []int{2}
}

type RespCtrlReprov struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespCtrlReprov) Reset() {
	*x = RespCtrlReprov{}
	mi := &file_wifi_ctrl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespCtrlReprov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespCtrlReprov) ProtoMessage() {}

func (x *RespCtrlReprov) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_ctrl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespCtrlReprov.ProtoReflect.Descriptor instead.
func (*RespCtrlReprov) Descriptor() ([]byte, []int) {
	return file_wifi_ctrl_proto_rawDescGZIP(), []int{3}
}

type WiFiCtrlPayload struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Msg    WiFiCtrlMsgType        `protobuf:"varint,1,opt,name=msg,proto3,enum=WiFiCtrlMsgType" json:"msg,omitempty"`
	Status Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WiFiCtrlPayload_CmdCtrlReset
	//	*WiFiCtrlPayload_RespCtrlReset
	//	*WiFiCtrlPayload_CmdCtrlReprov
	//	*WiFiCtrlPayload_RespCtrlReprov
	Payload       isWiFiCtrlPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WiFiCtrlPayload) Reset() {
	*x = WiFiCtrlPayload{}
	mi := &file_wifi_ctrl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WiFiCtrlPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiCtrlPayload) ProtoMessage() {}

func (x *WiFiCtrlPayload) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_ctrl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiCtrlPayload.ProtoReflect.Descriptor instead.
func (*WiFiCtrlPayload) Descriptor() ([]byte, []int) {
	return file_wifi_ctrl_proto_rawDescGZIP(), []int{4}
}

func (x *WiFiCtrlPayload) GetMsg() WiFiCtrlMsgType {
	if x != nil {
		return x.Msg
	}
	return WiFiCtrlMsgType_TypeCtrlReserved
}

func (x *WiFiCtrlPayload) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

func (x *WiFiCtrlPayload) GetPayload() isWiFiCtrlPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WiFiCtrlPayload) GetCmdCtrlReset() *CmdCtrlReset {
	if x != nil {
		if x, ok := x.Payload.(*WiFiCtrlPayload_CmdCtrlReset); ok {
			return x.CmdCtrlReset
		}
	}
	return nil
}

func (x *WiFiCtrlPayload) GetRespCtrlReset() *RespCtrlReset {
	if x != nil {
		if x, ok := x.Payload.(*WiFiCtrlPayload_RespCtrlReset); ok {
			return x.RespCtrlReset
		}
	}
	return nil
}

func (x *WiFiCtrlPayload) GetCmdCtrlReprov() *CmdCtrlReprov {
	if x != nil {
		if x, ok := x.Payload.(*WiFiCtrlPayload_CmdCtrlReprov); ok {
			return x.CmdCtrlReprov
		}
	}
	return nil
}

func (x *WiFiCtrlPayload) GetRespCtrlReprov() *RespCtrlReprov {
	if x != nil {
		if x, ok := x.Payload.(*WiFiCtrlPayload_RespCtrlReprov); ok {
			return x.RespCtrlReprov
		}
	}
	return nil
}

type isWiFiCtrlPayload_Payload interface {
	isWiFiCtrlPayload_Payload()
}

type WiFiCtrlPayload_CmdCtrlReset struct {
	CmdCtrlReset *CmdCtrlReset `protobuf:"bytes,11,opt,name=cmd_ctrl_reset,json=cmdCtrlReset,proto3,oneof"`
}

type WiFiCtrlPayload_RespCtrlReset struct {
	RespCtrlReset *RespCtrlReset `protobuf:"bytes,12,opt,name=resp_ctrl_reset,json=respCtrlReset,proto3,oneof"`
}

type WiFiCtrlPayload_CmdCtrlReprov struct {
	CmdCtrlReprov *CmdCtrlReprov `protobuf:"bytes,13,opt,name=cmd_ctrl_reprov,json=cmdCtrlReprov,proto3,oneof"`
}

type WiFiCtrlPayload_RespCtrlReprov struct {
	RespCtrlReprov *RespCtrlReprov `protobuf:"bytes,14,opt,name=resp_ctrl_reprov,json=respCtrlReprov,proto3,oneof"`
}

func (*WiFiCtrlPayload_CmdCtrlReset) isWiFiCtrlPayload_Payload() {}

func (*WiFiCtrlPayload_RespCtrlReset) isWiFiCtrlPayload_Payload() {}

func (*WiFiCtrlPayload_CmdCtrlReprov) isWiFiCtrlPayload_Payload() {}

func (*WiFiCtrlPayload_RespCtrlReprov) isWiFiCtrlPayload_Payload() {}

var File_wifi_ctrl_proto protoreflect.FileDescriptor

const file_wifi_ctrl_proto_rawDesc = "" +
	"\n" +
	"\x0fwifi_ctrl.proto\x1a\x0fconstants.proto\"\x0e\n" +
	"\fCmdCtrlReset\"\x0f\n" +
	"\rRespCtrlReset\"\x0f\n" +
	"\rCmdCtrlReprov\"\x10\n" +
	"\x0eRespCtrlReprov\"\xc9\x02\n" +
	"\x0fWiFiCtrlPayload\x12\"\n" +
	"\x03msg\x18\x01 \x01(\x0e2\x10.WiFiCtrlMsgTypeR\x03msg\x12\x1f\n" +
	"\x06status\x18\x02 \x01(\x0e2\a.StatusR\x06status\x125\n" +
	"\x0ecmd_ctrl_reset\x18\v \x01(\v2\r.CmdCtrlResetH\x00R\fcmdCtrlReset\x128\n" +
	"\x0fresp_ctrl_reset\x18\f \x01(\v2\x0e.RespCtrlResetH\x00R\rrespCtrlReset\x128\n" +
	"\x0fcmd_ctrl_reprov\x18\r \x01(\v2\x0e.CmdCtrlReprovH\x00R\rcmdCtrlReprov\x12;\n" +
	"\x10resp_ctrl_reprov\x18\x0e \x01(\v2\x0f.RespCtrlReprovH\x00R\x0erespCtrlReprovB\t\n" +
	"\apayload*\x83\x01\n" +
	"\x0fWiFiCtrlMsgType\x12\x14\n" +
	"\x10TypeCtrlReserved\x10\x00\x12\x14\n" +
	"\x10TypeCmdCtrlReset\x10\x01\x12\x15\n" +
	"\x11TypeRespCtrlReset\x10\x02\x12\x15\n" +
	"\x11TypeCmdCtrlReprov\x10\x03\x12\x16\n" +
	"\x12TypeRespCtrlReprov\x10\x04BSZQgithub.com/go-go-golems/almanach/internal/provisioning/native/proto/espidf;espidfb\x06proto3"

var (
	file_wifi_ctrl_proto_rawDescOnce sync.Once
	file_wifi_ctrl_proto_rawDescData []byte
)

func file_wifi_ctrl_proto_rawDescGZIP() []byte {
	file_wifi_ctrl_proto_rawDescOnce.Do(func() {
		file_wifi_ctrl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wifi_ctrl_proto_rawDesc), len(file_wifi_ctrl_proto_rawDesc)))
	})
	return file_wifi_ctrl_proto_rawDescData
}

var file_wifi_ctrl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wifi_ctrl_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_wifi_ctrl_proto_goTypes = []any{
	(WiFiCtrlMsgType)(0),    // 0: WiFiCtrlMsgType
	(*CmdCtrlReset)(nil),    // 1: CmdCtrlReset
	(*RespCtrlReset)(nil),   // 2: RespCtrlReset
	(*CmdCtrlReprov)(nil),   // 3: CmdCtrlReprov
	(*RespCtrlReprov)(nil),  // 4: RespCtrlReprov
	(*WiFiCtrlPayload)(nil), // 5: WiFiCtrlPayload
	(Status)(0),             // 6: Status
}
var file_wifi_ctrl_proto_depIdxs = []int32{
	0, // 0: WiFiCtrlPayload.msg:type_name -> WiFiCtrlMsgType
	6, // 1: WiFiCtrlPayload.status:type_name -> Status
	1, // 2: WiFiCtrlPayload.cmd_ctrl_reset:type_name -> CmdCtrlReset
	2, // 3: WiFiCtrlPayload.resp_ctrl_reset:type_name -> RespCtrlReset
	3, // 4: WiFiCtrlPayload.cmd_ctrl_reprov:type_name -> CmdCtrlReprov
	4, // 5: WiFiCtrlPayload.resp_ctrl_reprov:type_name -> RespCtrlReprov
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_wifi_ctrl_proto_init() }
func file_wifi_ctrl_proto_init() {
	if File_wifi_ctrl_proto != nil {
		return
	}
	file_constants_proto_init()
	file_wifi_ctrl_proto_msgTypes[4].OneofWrappers = []any{
		(*WiFiCtrlPayload_CmdCtrlReset)(nil),
		(*WiFiCtrlPayload_RespCtrlReset)(nil),
		(*WiFiCtrlPayload_CmdCtrlReprov)(nil),
		(*WiFiCtrlPayload_RespCtrlReprov)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_ctrl_proto_rawDesc), len(file_wifi_ctrl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_ctrl_proto_goTypes,
		DependencyIndexes: file_wifi_ctrl_proto_depIdxs,
		EnumInfos:         file_wifi_ctrl_proto_enumTypes,
		MessageInfos:      file_wifi_ctrl_proto_msgTypes,
	}.Build()
	File_wifi_ctrl_proto = out.File
	file_wifi_ctrl_proto_goTypes = nil
	file_wifi_ctrl_proto_depIdxs = nil
}
