// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi_constants.proto

package espidf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WifiStationState int32

const (
	WifiStationState_Connected        WifiStationState = 0
	WifiStationState_Connecting       WifiStationState = 1
	WifiStationState_Disconnected     WifiStationState = 2
	WifiStationState_ConnectionFailed WifiStationState = 3
)

// Enum value maps for WifiStationState.
var (
	WifiStationState_name = map[int32]string{
		0: "Connected",
		1: "Connecting",
		2: "Disconnected",
		3: "ConnectionFailed",
	}
	WifiStationState_value = map[string]int32{
		"Connected":        0,
		"Connecting":       1,
		"Disconnected":     2,
		"ConnectionFailed": 3,
	}
)

func (x WifiStationState) Enum() *WifiStationState {
	p := new(WifiStationState)
	*p = x
	return p
}

func (x WifiStationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiStationState) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_constants_proto_enumTypes[0].Descriptor()
}

func (WifiStationState) Type() protoreflect.EnumType {
	return &file_wifi_constants_proto_enumTypes[0]
}

func (x WifiStationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiStationState.Descriptor instead.
func (WifiStationState) EnumDescriptor() ([]byte, []int) {
	return file_wifi_constants_proto_rawDescGZIP(), []int{0}
}

type WifiConnectFailedReason int32

const (
	WifiConnectFailedReason_AuthError       WifiConnectFailedReason = 0
	WifiConnectFailedReason_NetworkNotFound WifiConnectFailedReason = 1
)

// Enum value maps for WifiConnectFailedReason.
var (
	WifiConnectFailedReason_name = map[int32]string{
		0: "AuthError",
		1: "NetworkNotFound",
	}
	WifiConnectFailedReason_value = map[string]int32{
		"AuthError":       0,
		"NetworkNotFound": 1,
	}
)

func (x WifiConnectFailedReason) Enum() *WifiConnectFailedReason {
	p := new(WifiConnectFailedReason)
	*p = x
	return p
}

func (x WifiConnectFailedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiConnectFailedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_constants_proto_enumTypes[1].Descriptor()
}

func (WifiConnectFailedReason) Type() protoreflect.EnumType {
	return &file_wifi_constants_proto_enumTypes[1]
}

func (x WifiConnectFailedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiConnectFailedReason.Descriptor instead.
func (WifiConnectFailedReason) EnumDescriptor() ([]byte, []int) {
	return file_wifi_constants_proto_rawDescGZIP(), []int{1}
}

type WifiAuthMode int32

const (
	WifiAuthMode_Open            WifiAuthMode = 0
	WifiAuthMode_WEP             WifiAuthMode = 1
	WifiAuthMode_WPA_PSK         WifiAuthMode = 2
	WifiAuthMode_WPA2_PSK        WifiAuthMode = 3
	WifiAuthMode_WPA_WPA2_PSK    WifiAuthMode = 4
	WifiAuthMode_WPA2_ENTERPRISE WifiAuthMode = 5
	WifiAuthMode_WPA3_PSK        WifiAuthMode = 6
	WifiAuthMode_WPA2_WPA3_PSK   WifiAuthMode = 7
)

// Enum value maps for WifiAuthMode.
var (
	WifiAuthMode_name = map[int32]string{
		0: "Open",
		1: "WEP",
		2: "WPA_PSK",
		3: "WPA2_PSK",
		4: "WPA_WPA2_PSK",
		5: "WPA2_ENTERPRISE",
		6: "WPA3_PSK",
		7: "WPA2_WPA3_PSK",
	}
	WifiAuthMode_value = map[string]int32{
		"Open":            0,
		"WEP":             1,
		"WPA_PSK":         2,
		"WPA2_PSK":        3,
		"WPA_WPA2_PSK":    4,
		"WPA2_ENTERPRISE": 5,
		"WPA3_PSK":        6,
		"WPA2_WPA3_PSK":   7,
	}
)

func (x WifiAuthMode) Enum() *WifiAuthMode {
	p := new(WifiAuthMode)
	*p = x
	return p
}

func (x WifiAuthMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WifiAuthMode) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_constants_proto_enumTypes[2].Descriptor()
}

func (WifiAuthMode) Type() protoreflect.EnumType {
	return &file_wifi_constants_proto_enumTypes[2]
}

func (x WifiAuthMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WifiAuthMode.Descriptor instead.
func (WifiAuthMode) EnumDescriptor() ([]byte, []int) {
	return file_wifi_constants_proto_rawDescGZIP(), []int{2}
}

type WifiAttemptFailed struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttemptsRemaining uint32                 `protobuf:"varint,1,opt,name=attempts_remaining,json=attemptsRemaining,proto3" json:"attempts_remaining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WifiAttemptFailed) Reset() {
	*x = WifiAttemptFailed{}
	mi := &file_wifi_constants_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiAttemptFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiAttemptFailed) ProtoMessage() {}

func (x *WifiAttemptFailed) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_constants_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiAttemptFailed.ProtoReflect.Descriptor instead.
func (*WifiAttemptFailed) Descriptor() ([]byte, []int) {
	return file_wifi_constants_proto_rawDescGZIP(), []int{0}
}

func (x *WifiAttemptFailed) GetAttemptsRemaining() uint32 {
	if x != nil {
		return x.AttemptsRemaining
	}
	return 0
}

type WifiConnectedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip4Addr       string                 `protobuf:"bytes,1,opt,name=ip4_addr,json=ip4Addr,proto3" json:"ip4_addr,omitempty"`
	AuthMode      WifiAuthMode           `protobuf:"varint,2,opt,name=auth_mode,json=authMode,proto3,enum=WifiAuthMode" json:"auth_mode,omitempty"`
	Ssid          []byte                 `protobuf:"bytes,3,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Bssid         []byte                 `protobuf:"bytes,4,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Channel       int32                  `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiConnectedState) Reset() {
	*x = WifiConnectedState{}
	mi := &file_wifi_constants_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiConnectedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiConnectedState) ProtoMessage() {}

func (x *WifiConnectedState) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_constants_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiConnectedState.ProtoReflect.Descriptor instead.
func (*WifiConnectedState) Descriptor() ([]byte, []int) {
	return file_wifi_constants_proto_rawDescGZIP(), []int{1}
}

func (x *WifiConnectedState) GetIp4Addr() string {
	if x != nil {
		return x.Ip4Addr
	}
	return ""
}

func (x *WifiConnectedState) GetAuthMode() WifiAuthMode {
	if x != nil {
		return x.AuthMode
	}
	return WifiAuthMode_Open
}

func (x *WifiConnectedState) GetSsid() []byte {
	if x != nil {
		return x.Ssid
	}
	return nil
}

func (x *WifiConnectedState) GetBssid() []byte {
	if x != nil {
		return x.Bssid
	}
	return nil
}

func (x *WifiConnectedState) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

var File_wifi_constants_proto protoreflect.FileDescriptor

const file_wifi_constants_proto_rawDesc = "" +
	"\n" +
	"\x14wifi_constants.proto\"B\n" +
	"\x11WifiAttemptFailed\x12-\n" +
	"\x12attempts_remaining\x18\x01 \x01(\rR\x11attemptsRemaining\"\x9f\x01\n" +
	"\x12WifiConnectedState\x12\x19\n" +
	"\bip4_addr\x18\x01 \x01(\tR\aip4Addr\x12*\n" +
	"\tauth_mode\x18\x02 \x01(\x0e2\r.WifiAuthModeR\bauthMode\x12\x12\n" +
	"\x04ssid\x18\x03 \x01(\fR\x04ssid\x12\x14\n" +
	"\x05bssid\x18\x04 \x01(\fR\x05bssid\x12\x18\n" +
	"\achannel\x18\x05 \x01(\x05R\achannel*Y\n" +
	"\x10WifiStationState\x12\r\n" +
	"\tConnected\x10\x00\x12\x0e\n" +
	"\n" +
	"Connecting\x10\x01\x12\x10\n" +
	"\fDisconnected\x10\x02\x12\x14\n" +
	"\x10ConnectionFailed\x10\x03*=\n" +
	"\x17WifiConnectFailedReason\x12\r\n" +
	"\tAuthError\x10\x00\x12\x13\n" +
	"\x0fNetworkNotFound\x10\x01*\x84\x01\n" +
	"\fWifiAuthMode\x12\b\n" +
	"\x04Open\x10\x00\x12\a\n" +
	"\x03WEP\x10\x01\x12\v\n" +
	"\aWPA_PSK\x10\x02\x12\f\n" +
	"\bWPA2_PSK\x10\x03\x12\x10\n" +
	"\fWPA_WPA2_PSK\x10\x04\x12\x13\n" +
	"\x0fWPA2_ENTERPRISE\x10\x05\x12\f\n" +
	"\bWPA3_PSK\x10\x06\x12\x11\n" +
	"\rWPA2_WPA3_PSK\x10\aBSZQgithub.com/go-go-golems/almanach/internal/provisioning/native/proto/espidf;espidfb\x06proto3"

var (
	file_wifi_constants_proto_rawDescOnce sync.Once
	file_wifi_constants_proto_rawDescData []byte
)

func file_wifi_constants_proto_rawDescGZIP() []byte {
	file_wifi_constants_proto_rawDescOnce.Do(func() {
		file_wifi_constants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wifi_constants_proto_rawDesc), len(file_wifi_constants_proto_rawDesc)))
	})
	return file_wifi_constants_proto_rawDescData
}

var file_wifi_constants_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_wifi_constants_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wifi_constants_proto_goTypes = []any{
	(WifiStationState)(0),        // 0: WifiStationState
	(WifiConnectFailedReason)(0), // 1: WifiConnectFailedReason
	(WifiAuthMode)(0),            // 2: WifiAuthMode
	(*WifiAttemptFailed)(nil),    // 3: WifiAttemptFailed
	(*WifiConnectedState)(nil),   // 4: WifiConnectedState
}
var file_wifi_constants_proto_depIdxs = []int32{
	2, // 0: WifiConnectedState.auth_mode:type_name -> WifiAuthMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_wifi_constants_proto_init() }
func file_wifi_constants_proto_init() {
	if File_wifi_constants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_constants_proto_rawDesc), len(file_wifi_constants_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_constants_proto_goTypes,
		DependencyIndexes: file_wifi_constants_proto_depIdxs,
		EnumInfos:         file_wifi_constants_proto_enumTypes,
		MessageInfos:      file_wifi_constants_proto_msgTypes,
	}.Build()
	File_wifi_constants_proto = out.File
	file_wifi_constants_proto_goTypes = nil
	file_wifi_constants_proto_depIdxs = nil
}
