// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: wifi_scan.proto

package espidf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WiFiScanMsgType int32

const (
	WiFiScanMsgType_TypeCmdScanStart   WiFiScanMsgType = 0
	WiFiScanMsgType_TypeRespScanStart  WiFiScanMsgType = 1
	WiFiScanMsgType_TypeCmdScanStatus  WiFiScanMsgType = 2
	WiFiScanMsgType_TypeRespScanStatus WiFiScanMsgType = 3
	WiFiScanMsgType_TypeCmdScanResult  WiFiScanMsgType = 4
	WiFiScanMsgType_TypeRespScanResult WiFiScanMsgType = 5
)

// Enum value maps for WiFiScanMsgType.
var (
	WiFiScanMsgType_name = map[int32]string{
		0: "TypeCmdScanStart",
		1: "TypeRespScanStart",
		2: "TypeCmdScanStatus",
		3: "TypeRespScanStatus",
		4: "TypeCmdScanResult",
		5: "TypeRespScanResult",
	}
	WiFiScanMsgType_value = map[string]int32{
		"TypeCmdScanStart":   0,
		"TypeRespScanStart":  1,
		"TypeCmdScanStatus":  2,
		"TypeRespScanStatus": 3,
		"TypeCmdScanResult":  4,
		"TypeRespScanResult": 5,
	}
)

func (x WiFiScanMsgType) Enum() *WiFiScanMsgType {
	p := new(WiFiScanMsgType)
	*p = x
	return p
}

func (x WiFiScanMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WiFiScanMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_wifi_scan_proto_enumTypes[0].Descriptor()
}

func (WiFiScanMsgType) Type() protoreflect.EnumType {
	return &file_wifi_scan_proto_enumTypes[0]
}

func (x WiFiScanMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WiFiScanMsgType.Descriptor instead.
func (WiFiScanMsgType) EnumDescriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{0}
}

type CmdScanStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocking      bool                   `protobuf:"varint,1,opt,name=blocking,proto3" json:"blocking,omitempty"`
	Passive       bool                   `protobuf:"varint,2,opt,name=passive,proto3" json:"passive,omitempty"`
	GroupChannels uint32                 `protobuf:"varint,3,opt,name=group_channels,json=groupChannels,proto3" json:"group_channels,omitempty"`
	PeriodMs      uint32                 `protobuf:"varint,4,opt,name=period_ms,json=periodMs,proto3" json:"period_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdScanStart) Reset() {
	*x = CmdScanStart{}
	mi := &file_wifi_scan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdScanStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdScanStart) ProtoMessage() {}

func (x *CmdScanStart) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_scan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdScanStart.ProtoReflect.Descriptor instead.
func (*CmdScanStart) Descriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{0}
}

func (x *CmdScanStart) GetBlocking() bool {
	if x != nil {
		return x.Blocking
	}
	return false
}

func (x *CmdScanStart) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *CmdScanStart) GetGroupChannels() uint32 {
	if x != nil {
		return x.GroupChannels
	}
	return 0
}

func (x *CmdScanStart) GetPeriodMs() uint32 {
	if x != nil {
		return x.PeriodMs
	}
	return 0
}

type RespScanStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespScanStart) Reset() {
	*x = RespScanStart{}
	mi := &file_wifi_scan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespScanStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespScanStart) ProtoMessage() {}

func (x *RespScanStart) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_scan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespScanStart.ProtoReflect.Descriptor instead.
func (*RespScanStart) Descriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{1}
}

type CmdScanStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdScanStatus) Reset() {
	*x = CmdScanStatus{}
	mi := &file_wifi_scan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdScanStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdScanStatus) ProtoMessage() {}

func (x *CmdScanStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_scan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdScanStatus.ProtoReflect.Descriptor instead.
func (*CmdScanStatus) Descriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{2}
}

type RespScanStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanFinished  bool                   `protobuf:"varint,1,opt,name=scan_finished,json=scanFinished,proto3" json:"scan_finished,omitempty"`
	ResultCount   uint32                 `protobuf:"varint,2,opt,name=result_count,json=resultCount,proto3" json:"result_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespScanStatus) Reset() {
	*x = RespScanStatus{}
	mi := &file_wifi_scan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespScanStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespScanStatus) ProtoMessage() {}

func (x *RespScanStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_scan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespScanStatus.ProtoReflect.Descriptor instead.
func (*RespScanStatus) Descriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{3}
}

func (x *RespScanStatus) GetScanFinished() bool {
	if x != nil {
		return x.ScanFinished
	}
	return false
}

func (x *RespScanStatus) GetResultCount() uint32 {
	if x != nil {
		return x.ResultCount
	}
	return 0
}

type CmdScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartIndex    uint32                 `protobuf:"varint,1,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdScanResult) Reset() {
	*x = CmdScanResult{}
	mi := &file_wifi_scan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdScanResult) ProtoMessage() {}

func (x *CmdScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_scan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdScanResult.ProtoReflect.Descriptor instead.
func (*CmdScanResult) Descriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{4}
}

func (x *CmdScanResult) GetStartIndex() uint32 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *CmdScanResult) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type WiFiScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ssid          []byte                 `protobuf:"bytes,1,opt,name=ssid,proto3" json:"ssid,omitempty"`
	Channel       uint32                 `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Rssi          int32                  `protobuf:"varint,3,opt,name=rssi,proto3" json:"rssi,omitempty"`
	Bssid         []byte                 `protobuf:"bytes,4,opt,name=bssid,proto3" json:"bssid,omitempty"`
	Auth          WifiAuthMode           `protobuf:"varint,5,opt,name=auth,proto3,enum=WifiAuthMode" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WiFiScanResult) Reset() {
	*x = WiFiScanResult{}
	mi := &file_wifi_scan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WiFiScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiScanResult) ProtoMessage() {}

func (x *WiFiScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_scan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiScanResult.ProtoReflect.Descriptor instead.
func (*WiFiScanResult) Descriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{5}
}

func (x *WiFiScanResult) GetSsid() []byte {
	if x != nil {
		return x.Ssid
	}
	return nil
}

func (x *WiFiScanResult) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *WiFiScanResult) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *WiFiScanResult) GetBssid() []byte {
	if x != nil {
		return x.Bssid
	}
	return nil
}

func (x *WiFiScanResult) GetAuth() WifiAuthMode {
	if x != nil {
		return x.Auth
	}
	return WifiAuthMode_Open
}

type RespScanResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*WiFiScanResult      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespScanResult) Reset() {
	*x = RespScanResult{}
	mi := &file_wifi_scan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespScanResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespScanResult) ProtoMessage() {}

func (x *RespScanResult) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_scan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespScanResult.ProtoReflect.Descriptor instead.
func (*RespScanResult) Descriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{6}
}

func (x *RespScanResult) GetEntries() []*WiFiScanResult {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WiFiScanPayload struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Msg    WiFiScanMsgType        `protobuf:"varint,1,opt,name=msg,proto3,enum=WiFiScanMsgType" json:"msg,omitempty"`
	Status Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WiFiScanPayload_CmdScanStart
	//	*WiFiScanPayload_RespScanStart
	//	*WiFiScanPayload_CmdScanStatus
	//	*WiFiScanPayload_RespScanStatus
	//	*WiFiScanPayload_CmdScanResult
	//	*WiFiScanPayload_RespScanResult
	Payload       isWiFiScanPayload_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WiFiScanPayload) Reset() {
	*x = WiFiScanPayload{}
	mi := &file_wifi_scan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WiFiScanPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiFiScanPayload) ProtoMessage() {}

func (x *WiFiScanPayload) ProtoReflect() protoreflect.Message {
	mi := &file_wifi_scan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiFiScanPayload.ProtoReflect.Descriptor instead.
func (*WiFiScanPayload) Descriptor() ([]byte, []int) {
	return file_wifi_scan_proto_rawDescGZIP(), []int{7}
}

func (x *WiFiScanPayload) GetMsg() WiFiScanMsgType {
	if x != nil {
		return x.Msg
	}
	return WiFiScanMsgType_TypeCmdScanStart
}

func (x *WiFiScanPayload) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Success
}

func (x *WiFiScanPayload) GetPayload() isWiFiScanPayload_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WiFiScanPayload) GetCmdScanStart() *CmdScanStart {
	if x != nil {
		if x, ok := x.Payload.(*WiFiScanPayload_CmdScanStart); ok {
			return x.CmdScanStart
		}
	}
	return nil
}

func (x *WiFiScanPayload) GetRespScanStart() *RespScanStart {
	if x != nil {
		if x, ok := x.Payload.(*WiFiScanPayload_RespScanStart); ok {
			return x.RespScanStart
		}
	}
	return nil
}

func (x *WiFiScanPayload) GetCmdScanStatus() *CmdScanStatus {
	if x != nil {
		if x, ok := x.Payload.(*WiFiScanPayload_CmdScanStatus); ok {
			return x.CmdScanStatus
		}
	}
	return nil
}

func (x *WiFiScanPayload) GetRespScanStatus() *RespScanStatus {
	if x != nil {
		if x, ok := x.Payload.(*WiFiScanPayload_RespScanStatus); ok {
			return x.RespScanStatus
		}
	}
	return nil
}

func (x *WiFiScanPayload) GetCmdScanResult() *CmdScanResult {
	if x != nil {
		if x, ok := x.Payload.(*WiFiScanPayload_CmdScanResult); ok {
			return x.CmdScanResult
		}
	}
	return nil
}

func (x *WiFiScanPayload) GetRespScanResult() *RespScanResult {
	if x != nil {
		if x, ok := x.Payload.(*WiFiScanPayload_RespScanResult); ok {
			return x.RespScanResult
		}
	}
	return nil
}

type isWiFiScanPayload_Payload interface {
	isWiFiScanPayload_Payload()
}

type WiFiScanPayload_CmdScanStart struct {
	CmdScanStart *CmdScanStart `protobuf:"bytes,10,opt,name=cmd_scan_start,json=cmdScanStart,proto3,oneof"`
}

type WiFiScanPayload_RespScanStart struct {
	RespScanStart *RespScanStart `protobuf:"bytes,11,opt,name=resp_scan_start,json=respScanStart,proto3,oneof"`
}

type WiFiScanPayload_CmdScanStatus struct {
	CmdScanStatus *CmdScanStatus `protobuf:"bytes,12,opt,name=cmd_scan_status,json=cmdScanStatus,proto3,oneof"`
}

type WiFiScanPayload_RespScanStatus struct {
	RespScanStatus *RespScanStatus `protobuf:"bytes,13,opt,name=resp_scan_status,json=respScanStatus,proto3,oneof"`
}

type WiFiScanPayload_CmdScanResult struct {
	CmdScanResult *CmdScanResult `protobuf:"bytes,14,opt,name=cmd_scan_result,json=cmdScanResult,proto3,oneof"`
}

type WiFiScanPayload_RespScanResult struct {
	RespScanResult *RespScanResult `protobuf:"bytes,15,opt,name=resp_scan_result,json=respScanResult,proto3,oneof"`
}

func (*WiFiScanPayload_CmdScanStart) isWiFiScanPayload_Payload() {}

func (*WiFiScanPayload_RespScanStart) isWiFiScanPayload_Payload() {}

func (*WiFiScanPayload_CmdScanStatus) isWiFiScanPayload_Payload() {}

func (*WiFiScanPayload_RespScanStatus) isWiFiScanPayload_Payload() {}

func (*WiFiScanPayload_CmdScanResult) isWiFiScanPayload_Payload() {}

func (*WiFiScanPayload_RespScanResult) isWiFiScanPayload_Payload() {}

var File_wifi_scan_proto protoreflect.FileDescriptor

const file_wifi_scan_proto_rawDesc = "" +
	"\n" +
	"\x0fwifi_scan.proto\x1a\x0fconstants.proto\x1a\x14wifi_constants.proto\"\x88\x01\n" +
	"\fCmdScanStart\x12\x1a\n" +
	"\bblocking\x18\x01 \x01(\bR\bblocking\x12\x18\n" +
	"\apassive\x18\x02 \x01(\bR\apassive\x12%\n" +
	"\x0egroup_channels\x18\x03 \x01(\rR\rgroupChannels\x12\x1b\n" +
	"\tperiod_ms\x18\x04 \x01(\rR\bperiodMs\"\x0f\n" +
	"\rRespScanStart\"\x0f\n" +
	"\rCmdScanStatus\"X\n" +
	"\x0eRespScanStatus\x12#\n" +
	"\rscan_finished\x18\x01 \x01(\bR\fscanFinished\x12!\n" +
	"\fresult_count\x18\x02 \x01(\rR\vresultCount\"F\n" +
	"\rCmdScanResult\x12\x1f\n" +
	"\vstart_index\x18\x01 \x01(\rR\n" +
	"startIndex\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\x8b\x01\n" +
	"\x0eWiFiScanResult\x12\x12\n" +
	"\x04ssid\x18\x01 \x01(\fR\x04ssid\x12\x18\n" +
	"\achannel\x18\x02 \x01(\rR\achannel\x12\x12\n" +
	"\x04rssi\x18\x03 \x01(\x05R\x04rssi\x12\x14\n" +
	"\x05bssid\x18\x04 \x01(\fR\x05bssid\x12!\n" +
	"\x04auth\x18\x05 \x01(\x0e2\r.WifiAuthModeR\x04auth\";\n" +
	"\x0eRespScanResult\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.WiFiScanResultR\aentries\"\xc0\x03\n" +
	"\x0fWiFiScanPayload\x12\"\n" +
	"\x03msg\x18\x01 \x01(\x0e2\x10.WiFiScanMsgTypeR\x03msg\x12\x1f\n" +
	"\x06status\x18\x02 \x01(\x0e2\a.StatusR\x06status\x125\n" +
	"\x0ecmd_scan_start\x18\n" +
	" \x01(\v2\r.CmdScanStartH\x00R\fcmdScanStart\x128\n" +
	"\x0fresp_scan_start\x18\v \x01(\v2\x0e.RespScanStartH\x00R\rrespScanStart\x128\n" +
	"\x0fcmd_scan_status\x18\f \x01(\v2\x0e.CmdScanStatusH\x00R\rcmdScanStatus\x12;\n" +
	"\x10resp_scan_status\x18\r \x01(\v2\x0f.RespScanStatusH\x00R\x0erespScanStatus\x128\n" +
	"\x0fcmd_scan_result\x18\x0e \x01(\v2\x0e.CmdScanResultH\x00R\rcmdScanResult\x12;\n" +
	"\x10resp_scan_result\x18\x0f \x01(\v2\x0f.RespScanResultH\x00R\x0erespScanResultB\t\n" +
	"\apayload*\x9c\x01\n" +
	"\x0fWiFiScanMsgType\x12\x14\n" +
	"\x10TypeCmdScanStart\x10\x00\x12\x15\n" +
	"\x11TypeRespScanStart\x10\x01\x12\x15\n" +
	"\x11TypeCmdScanStatus\x10\x02\x12\x16\n" +
	"\x12TypeRespScanStatus\x10\x03\x12\x15\n" +
	"\x11TypeCmdScanResult\x10\x04\x12\x16\n" +
	"\x12TypeRespScanResult\x10\x05BSZQgithub.com/go-go-golems/almanach/internal/provisioning/native/proto/espidf;espidfb\x06proto3"

var (
	file_wifi_scan_proto_rawDescOnce sync.Once
	file_wifi_scan_proto_rawDescData []byte
)

func file_wifi_scan_proto_rawDescGZIP() []byte {
	file_wifi_scan_proto_rawDescOnce.Do(func() {
		file_wifi_scan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wifi_scan_proto_rawDesc), len(file_wifi_scan_proto_rawDesc)))
	})
	return file_wifi_scan_proto_rawDescData
}

var file_wifi_scan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wifi_scan_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wifi_scan_proto_goTypes = []any{
	(WiFiScanMsgType)(0),    // 0: WiFiScanMsgType
	(*CmdScanStart)(nil),    // 1: CmdScanStart
	(*RespScanStart)(nil),   // 2: RespScanStart
	(*CmdScanStatus)(nil),   // 3: CmdScanStatus
	(*RespScanStatus)(nil),  // 4: RespScanStatus
	(*CmdScanResult)(nil),   // 5: CmdScanResult
	(*WiFiScanResult)(nil),  // 6: WiFiScanResult
	(*RespScanResult)(nil),  // 7: RespScanResult
	(*WiFiScanPayload)(nil), // 8: WiFiScanPayload
	(WifiAuthMode)(0),       // 9: WifiAuthMode
	(Status)(0),             // 10: Status
}
var file_wifi_scan_proto_depIdxs = []int32{
	9,  // 0: WiFiScanResult.auth:type_name -> WifiAuthMode
	6,  // 1: RespScanResult.entries:type_name -> WiFiScanResult
	0,  // 2: WiFiScanPayload.msg:type_name -> WiFiScanMsgType
	10, // 3: WiFiScanPayload.status:type_name -> Status
	1,  // 4: WiFiScanPayload.cmd_scan_start:type_name -> CmdScanStart
	2,  // 5: WiFiScanPayload.resp_scan_start:type_name -> RespScanStart
	3,  // 6: WiFiScanPayload.cmd_scan_status:type_name -> CmdScanStatus
	4,  // 7: WiFiScanPayload.resp_scan_status:type_name -> RespScanStatus
	5,  // 8: WiFiScanPayload.cmd_scan_result:type_name -> CmdScanResult
	7,  // 9: WiFiScanPayload.resp_scan_result:type_name -> RespScanResult
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_wifi_scan_proto_init() }
func file_wifi_scan_proto_init() {
	if File_wifi_scan_proto != nil {
		return
	}
	file_constants_proto_init()
	file_wifi_constants_proto_init()
	file_wifi_scan_proto_msgTypes[7].OneofWrappers = []any{
		(*WiFiScanPayload_CmdScanStart)(nil),
		(*WiFiScanPayload_RespScanStart)(nil),
		(*WiFiScanPayload_CmdScanStatus)(nil),
		(*WiFiScanPayload_RespScanStatus)(nil),
		(*WiFiScanPayload_CmdScanResult)(nil),
		(*WiFiScanPayload_RespScanResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wifi_scan_proto_rawDesc), len(file_wifi_scan_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wifi_scan_proto_goTypes,
		DependencyIndexes: file_wifi_scan_proto_depIdxs,
		EnumInfos:         file_wifi_scan_proto_enumTypes,
		MessageInfos:      file_wifi_scan_proto_msgTypes,
	}.Build()
	File_wifi_scan_proto = out.File
	file_wifi_scan_proto_goTypes = nil
	file_wifi_scan_proto_depIdxs = nil
}
