// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts,import_extension=none"
// @generated from file almanach/layout/v1/layout.proto (package almanach.layout.v1, syntax proto3)
/* eslint-disable */

// Almanach Layout DSL v2 — the block IR shared by the Go render/print service
// and the TypeScript studio. This schema is the single source of truth for the
// layout contract; both sides import code generated from it (see buf.gen.yaml).
//
// Transport is JSON: Go emits camelCase via protojson (UseProtoNames:false), the
// studio decodes with @bufbuild/protobuf fromJson / re-encodes with toJson.
//
// Phase 1 scope (ALMANACH-DSL-V2): types only — no behavior change. Block
// content is carried as google.protobuf.Struct (free-form JSON) for now; hot
// block types migrate to per-type messages in a oneof later.

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file almanach/layout/v1/layout.proto.
 */
export declare const file_almanach_layout_v1_layout: GenFile;

/**
 * A Layout is one almanach page: paper metadata, typography, a theme, an ordered
 * list of blocks, template data, and render options. It is what the Go service
 * hands to the studio and what the studio renders onto the paper strip.
 *
 * @generated from message almanach.layout.v1.Layout
 */
export declare type Layout = Message<"almanach.layout.v1.Layout"> & {
  /**
   * Bumped when the schema changes in a way consumers must gate on. Defaults to
   * the current version (SCHEMA_VERSION_V1) when unset.
   *
   * @generated from field: int32 schema_version = 1;
   */
  schemaVersion: number;

  /**
   * Paper width in printer dots (280-600, 384 for a 58mm head).
   *
   * @generated from field: int32 paper_width = 2;
   */
  paperWidth: number;

  /**
   * Blank lines fed after the page prints.
   *
   * @generated from field: int32 feed_lines = 3;
   */
  feedLines: number;

  /**
   * Name of a built-in theme to select (e.g. "minimal"). Ignored when
   * inline_theme is set.
   *
   * @generated from field: string theme = 4;
   */
  theme: string;

  /**
   * An inline theme carried by the layout itself — the "data-driven theme" case
   * (Phase 4). When present it takes precedence over `theme`.
   *
   * @generated from field: almanach.layout.v1.Theme inline_theme = 5;
   */
  inlineTheme?: Theme | undefined;

  /**
   * Typography presets for this layout. Merged over the built-in defaults; a
   * block may still override individual properties via Block.style.
   *
   * @generated from field: almanach.layout.v1.Typography typography = 6;
   */
  typography?: Typography | undefined;

  /**
   * The ordered blocks that make up the page.
   *
   * @generated from field: repeated almanach.layout.v1.Block blocks = 7;
   */
  blocks: Block[];

  /**
   * Template variables interpolated into block content (e.g. {{date}}).
   *
   * @generated from field: map<string, string> data = 8;
   */
  data: { [key: string]: string };

  /**
   * Page-level render/raster options. A block may override these per-block.
   *
   * @generated from field: almanach.layout.v1.RenderOptions render = 9;
   */
  render?: RenderOptions | undefined;
};

/**
 * Describes the message almanach.layout.v1.Layout.
 * Use `create(LayoutSchema)` to create a new message.
 */
export declare const LayoutSchema: GenMessage<Layout>;

/**
 * A single block on the page: an id, a dispatch `type` resolved against the
 * studio's renderer registry, typed style overrides, free-form content, and an
 * optional per-block render override.
 *
 * @generated from message almanach.layout.v1.Block
 */
export declare type Block = Message<"almanach.layout.v1.Block"> & {
  /**
   * Stable identifier, unique within the layout.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Dispatch key for the renderer registry (e.g. "title", "quote", "word").
   * Unknown types render a visible placeholder rather than vanishing.
   *
   * @generated from field: string type = 2;
   */
  type: string;

  /**
   * Inline typography overrides for this block's primary text. Shallow-merged
   * last: built-in preset default <- layout preset override <- this style.
   *
   * @generated from field: almanach.layout.v1.TextStyle style = 3;
   */
  style?: TextStyle | undefined;

  /**
   * Block content. Free-form JSON object for Phase 1; the shape is defined by
   * the block type's renderer. Migrates to typed per-type messages later.
   *
   * @generated from field: google.protobuf.Struct content = 4;
   */
  content?: JsonObject | undefined;

  /**
   * Optional per-block render/raster override (raster mode, threshold, printer
   * heat) for block-aware rasterization (Phase 6).
   *
   * @generated from field: almanach.layout.v1.RenderOptions render = 5;
   */
  render?: RenderOptions | undefined;
};

/**
 * Describes the message almanach.layout.v1.Block.
 * Use `create(BlockSchema)` to create a new message.
 */
export declare const BlockSchema: GenMessage<Block>;

/**
 * A concrete text style. Every field is optional; unset fields inherit from the
 * next layer down in the resolution chain (block <- layout preset <- built-in
 * default). Sizes are in CSS px as rendered on the 384-dot paper.
 *
 * @generated from message almanach.layout.v1.TextStyle
 */
export declare type TextStyle = Message<"almanach.layout.v1.TextStyle"> & {
  /**
   * CSS font-family stack (e.g. "'DejaVu Serif', serif").
   *
   * @generated from field: optional string font = 1;
   */
  font?: string | undefined;

  /**
   * font-size in px.
   *
   * @generated from field: optional double size = 2;
   */
  size?: number | undefined;

  /**
   * font-weight (100-900).
   *
   * @generated from field: optional int32 weight = 3;
   */
  weight?: number | undefined;

  /**
   * line-height as a unitless multiplier.
   *
   * @generated from field: optional double line_height = 4;
   */
  lineHeight?: number | undefined;

  /**
   * letter-spacing in em.
   *
   * @generated from field: optional double letter_spacing = 5;
   */
  letterSpacing?: number | undefined;

  /**
   * text-transform.
   *
   * @generated from field: almanach.layout.v1.TextCase text_case = 6;
   */
  textCase: TextCase;

  /**
   * font-style: italic.
   *
   * @generated from field: optional bool italic = 7;
   */
  italic?: boolean | undefined;

  /**
   * Floor for the resolved size in px — the paper-verified legibility guard so a
   * preset override or scale never drops text below what survives the 1-bit
   * threshold.
   *
   * @generated from field: optional double min_size = 8;
   */
  minSize?: number | undefined;
};

/**
 * Describes the message almanach.layout.v1.TextStyle.
 * Use `create(TextStyleSchema)` to create a new message.
 */
export declare const TextStyleSchema: GenMessage<TextStyle>;

/**
 * Named typography presets. A preset name (e.g. "title", "body", "caption") maps
 * to a TextStyle. Ships with built-in defaults that bake in the ALMANACH-PIXELFONT
 * recipe (bigger sizes, a hinted body font, bold for small/italic). A layout may
 * override any preset here; the built-in defaults fill the rest.
 *
 * @generated from message almanach.layout.v1.Typography
 */
export declare type Typography = Message<"almanach.layout.v1.Typography"> & {
  /**
   * @generated from field: map<string, almanach.layout.v1.TextStyle> presets = 1;
   */
  presets: { [key: string]: TextStyle };
};

/**
 * Describes the message almanach.layout.v1.Typography.
 * Use `create(TypographySchema)` to create a new message.
 */
export declare const TypographySchema: GenMessage<Typography>;

/**
 * Theme colors. Thermal output is monochrome, but colors are still meaningful
 * for the on-screen studio preview.
 *
 * @generated from message almanach.layout.v1.ThemeColors
 */
export declare type ThemeColors = Message<"almanach.layout.v1.ThemeColors"> & {
  /**
   * @generated from field: string paper = 1;
   */
  paper: string;

  /**
   * @generated from field: string ink = 2;
   */
  ink: string;

  /**
   * @generated from field: string muted = 3;
   */
  muted: string;

  /**
   * @generated from field: string accent = 4;
   */
  accent: string;

  /**
   * @generated from field: string rule = 5;
   */
  rule: string;
};

/**
 * Describes the message almanach.layout.v1.ThemeColors.
 * Use `create(ThemeColorsSchema)` to create a new message.
 */
export declare const ThemeColorsSchema: GenMessage<ThemeColors>;

/**
 * A theme as data (Phase 4): colors, the font families it draws from, and its
 * own preset overrides. Built-in themes are seed data of this shape; a layout
 * may carry one inline (Layout.inline_theme) to define or patch a theme with no
 * code change.
 *
 * @generated from message almanach.layout.v1.Theme
 */
export declare type Theme = Message<"almanach.layout.v1.Theme"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: almanach.layout.v1.ThemeColors colors = 2;
   */
  colors?: ThemeColors | undefined;

  /**
   * The font-family stacks this theme uses, in preference order. Fonts must be
   * present in the embedded font palette (web/src/fonts-embedded.css).
   *
   * @generated from field: repeated string font_palette = 3;
   */
  fontPalette: string[];

  /**
   * Preset overrides applied on top of the built-in typography defaults when
   * this theme is active.
   *
   * @generated from field: map<string, almanach.layout.v1.TextStyle> preset_overrides = 4;
   */
  presetOverrides: { [key: string]: TextStyle };
};

/**
 * Describes the message almanach.layout.v1.Theme.
 * Use `create(ThemeSchema)` to create a new message.
 */
export declare const ThemeSchema: GenMessage<Theme>;

/**
 * @generated from message almanach.layout.v1.RenderOptions
 */
export declare type RenderOptions = Message<"almanach.layout.v1.RenderOptions"> & {
  /**
   * CSS selector of the element to screenshot (page-level only).
   *
   * @generated from field: optional string selector = 1;
   */
  selector?: string | undefined;

  /**
   * 1-bit threshold, 0-255.
   *
   * @generated from field: optional uint32 threshold = 2;
   */
  threshold?: number | undefined;

  /**
   * Render oversampling factor; downscaled before 1-bit conversion.
   *
   * @generated from field: optional int32 supersample_scale = 3;
   */
  supersampleScale?: number | undefined;

  /**
   * @generated from field: optional int32 viewport_width = 4;
   */
  viewportWidth?: number | undefined;

  /**
   * @generated from field: optional int32 viewport_height = 5;
   */
  viewportHeight?: number | undefined;

  /**
   * Rasterization technique for this region.
   *
   * @generated from field: almanach.layout.v1.RasterMode raster_mode = 6;
   */
  rasterMode: RasterMode;

  /**
   * Tone-curve gamma applied before dithering (photos want ~0.8).
   *
   * @generated from field: optional double gamma = 7;
   */
  gamma?: number | undefined;

  /**
   * Printer head density/heat (text ~38, photos ~20).
   *
   * @generated from field: optional int32 printer_density = 8;
   */
  printerDensity?: number | undefined;

  /**
   * Printer feed speed.
   *
   * @generated from field: optional int32 printer_speed = 9;
   */
  printerSpeed?: number | undefined;
};

/**
 * Describes the message almanach.layout.v1.RenderOptions.
 * Use `create(RenderOptionsSchema)` to create a new message.
 */
export declare const RenderOptionsSchema: GenMessage<RenderOptions>;

/**
 * Text case transform, mirroring CSS text-transform.
 *
 * @generated from enum almanach.layout.v1.TextCase
 */
export enum TextCase {
  /**
   * @generated from enum value: TEXT_CASE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TEXT_CASE_NONE = 1;
   */
  NONE = 1,

  /**
   * @generated from enum value: TEXT_CASE_UPPER = 2;
   */
  UPPER = 2,

  /**
   * @generated from enum value: TEXT_CASE_LOWER = 3;
   */
  LOWER = 3,

  /**
   * @generated from enum value: TEXT_CASE_CAPITALIZE = 4;
   */
  CAPITALIZE = 4,
}

/**
 * Describes the enum almanach.layout.v1.TextCase.
 */
export declare const TextCaseSchema: GenEnum<TextCase>;

/**
 * How a screenshot region becomes a 1-bit bitmap and how the printer burns it.
 * Replaces the five hand-parsed `render:` keys with a validated message
 * (Phase 5). May appear page-level (Layout.render) or per-block (Block.render).
 *
 * @generated from enum almanach.layout.v1.RasterMode
 */
export enum RasterMode {
  /**
   * @generated from enum value: RASTER_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: RASTER_MODE_THRESHOLD = 1;
   */
  THRESHOLD = 1,

  /**
   * @generated from enum value: RASTER_MODE_ATKINSON = 2;
   */
  ATKINSON = 2,

  /**
   * @generated from enum value: RASTER_MODE_FLOYD_STEINBERG = 3;
   */
  FLOYD_STEINBERG = 3,

  /**
   * @generated from enum value: RASTER_MODE_BAYER = 4;
   */
  BAYER = 4,
}

/**
 * Describes the enum almanach.layout.v1.RasterMode.
 */
export declare const RasterModeSchema: GenEnum<RasterMode>;

